from pathlib import Path
# ==================================================================================================
# ARUNDA TRADER
# LIVE SIGNAL ELIGIBILITY + NO-TRADE SAFETY GATE v0.1
# ==================================================================================================
#
# PURPOSE
# -------
# Evaluate ONLY the newest FUSION_v0.5 live snapshot for:
#
#   1. Signal eligibility
#   2. No-trade safety
#   3. Arm completeness
#   4. Decision-input sufficiency
#
# IMPORTANT
# ---------
# This script:
#   - DOES NOT run fusion_engine
#   - DOES NOT modify production DB
#   - DOES NOT repair historical rows
#   - DOES NOT infer direction
#   - DOES NOT reconstruct score
#   - DOES NOT place orders
#   - DOES NOT inject live data
#
# Previously verified frontiers are treated as CLOSED/VERIFIED.
# This script consumes their output and moves ONE layer upward:
#
#       LIVE SIGNAL
#            |
#            v
#       ELIGIBILITY
#            |
#       +----+----+
#       |         |
#     TRADE     NO-TRADE
#
# Conservative by design.
# ==================================================================================================

import os
import sqlite3
import hashlib
import json
from datetime import datetime, timezone


# --------------------------------------------------------------------------------------------------
# CONFIGURATION
# --------------------------------------------------------------------------------------------------

PROJECT_ROOT = Path(r"C:\Users\ASUS\ArundaTrader")
PRODUCTION_DB = os.path.join(PROJECT_ROOT, "arunda.db")

# Existing disposable live capture generated by the previous frontier.
CAPTURE_ROOT = os.path.expandvars(
    r"C:\Users\ASUS\AppData\Local\Temp"
)

EXPECTED_ENGINE = "FUSION_v0.5"

# Conservative decision-safety thresholds.
#
# These are NOT used to reconstruct or alter signals.
# They are only used as a gate.
#
MIN_CONFIDENCE = 0.60
MIN_AVAILABLE_WEIGHT = 1.00

# Only fully populated input is eligible for a potential trade.
REQUIRED_DATA_QUALITY = "VERIFIED"
REQUIRED_SAFETY = "FULL_INPUT"

# Weak signals are explicitly blocked.
BLOCKED_SIGNAL_STRENGTH = {"WEAK"}

# Flat is never a trade candidate.
BLOCKED_DIRECTIONS = {"FLAT"}

# Only actual directional outputs can pass the directional gate.
ALLOWED_DIRECTIONS = {"LONG", "SHORT"}


# --------------------------------------------------------------------------------------------------
# UTILITIES
# --------------------------------------------------------------------------------------------------

def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        while True:
            chunk = f.read(1024 * 1024)

            if not chunk:
                break

            h.update(chunk)

    return h.hexdigest()


def find_latest_capture():
    candidates = []

    if not os.path.isdir(CAPTURE_ROOT):
        return None

    for name in os.listdir(CAPTURE_ROOT):

        if not name.startswith("arunda_live_launch_"):
            continue

        path = os.path.join(CAPTURE_ROOT, name)

        if not os.path.isdir(path):
            continue

        db_path = os.path.join(path, "arunda_live_capture.db")

        if not os.path.isfile(db_path):
            continue

        try:
            mtime = os.path.getmtime(db_path)
            candidates.append((mtime, path, db_path))
        except OSError:
            pass

    if not candidates:
        return None

    candidates.sort(reverse=True)

    return candidates[0][1], candidates[0][2]


def open_readonly(path):
    uri = "file:" + path.replace("\\", "/") + "?mode=ro"
    return sqlite3.connect(uri, uri=True)


def get_columns(conn):
    rows = conn.execute(
        "PRAGMA table_info(fusion_signals)"
    ).fetchall()

    return {row[1] for row in rows}


def utc_now():
    return datetime.now(timezone.utc)


# --------------------------------------------------------------------------------------------------
# PRODUCTION BASELINE
# --------------------------------------------------------------------------------------------------

def production_baseline():
    size = os.path.getsize(PRODUCTION_DB)
    digest = sha256_file(PRODUCTION_DB)

    conn = open_readonly(PRODUCTION_DB)

    try:
        rows = conn.execute(
            "SELECT COUNT(*) FROM fusion_signals"
        ).fetchone()[0]
    finally:
        conn.close()

    return {
        "size": size,
        "sha256": digest,
        "rows": rows,
    }


# --------------------------------------------------------------------------------------------------
# SNAPSHOT DISCOVERY
# --------------------------------------------------------------------------------------------------

def load_latest_snapshot(conn):
    row = conn.execute(
        """
        SELECT snapshot_id, MAX(timestamp)
        FROM fusion_signals
        WHERE engine_version = ?
          AND snapshot_id IS NOT NULL
        GROUP BY snapshot_id
        ORDER BY MAX(timestamp) DESC
        LIMIT 1
        """,
        (EXPECTED_ENGINE,),
    ).fetchone()

    if not row:
        raise RuntimeError("No FUSION_v0.5 snapshot found.")

    snapshot_id = row[0]

    rows = conn.execute(
        """
        SELECT
            id,
            timestamp,
            asset,
            market_available,
            positioning_available,
            news_available,
            available_weight,
            missing_arm_penalty,
            data_quality,
            direction,
            confidence,
            regime,
            signal_strength,
            entry_price,
            fused_score,
            snapshot_id,
            engine_version
        FROM fusion_signals
        WHERE snapshot_id = ?
          AND engine_version = ?
        ORDER BY id
        """,
        (snapshot_id, EXPECTED_ENGINE),
    ).fetchall()

    return snapshot_id, rows


# --------------------------------------------------------------------------------------------------
# ROW ELIGIBILITY
# --------------------------------------------------------------------------------------------------

def evaluate_row(row):
    (
        row_id,
        timestamp,
        asset,
        market_available,
        positioning_available,
        news_available,
        available_weight,
        missing_arm_penalty,
        data_quality,
        direction,
        confidence,
        regime,
        signal_strength,
        entry_price,
        fused_score,
        snapshot_id,
        engine_version,
    ) = row

    reasons = []

    # ----------------------------------------------------------------------------------------------
    # HARD INPUT SAFETY
    # ----------------------------------------------------------------------------------------------

    if engine_version != EXPECTED_ENGINE:
        reasons.append("ENGINE_MISMATCH")

    if not snapshot_id:
        reasons.append("MISSING_SNAPSHOT_ID")

    if not asset:
        reasons.append("MISSING_ASSET")

    if not timestamp:
        reasons.append("MISSING_TIMESTAMP")

    if entry_price is None:
        reasons.append("MISSING_ENTRY_PRICE")
    elif entry_price <= 0:
        reasons.append("INVALID_ENTRY_PRICE")

    if confidence is None:
        reasons.append("MISSING_CONFIDENCE")
    elif confidence < MIN_CONFIDENCE:
        reasons.append("CONFIDENCE_BELOW_GATE")

    if available_weight is None:
        reasons.append("MISSING_AVAILABLE_WEIGHT")
    elif available_weight < MIN_AVAILABLE_WEIGHT:
        reasons.append("INSUFFICIENT_AVAILABLE_WEIGHT")

    if data_quality != REQUIRED_DATA_QUALITY:
        reasons.append("DATA_QUALITY_NOT_VERIFIED")

    if direction not in ALLOWED_DIRECTIONS:
        if direction in BLOCKED_DIRECTIONS:
            reasons.append("FLAT_DIRECTION")
        else:
            reasons.append("INVALID_DIRECTION")

    if signal_strength in BLOCKED_SIGNAL_STRENGTH:
        reasons.append("WEAK_SIGNAL")

    if signal_strength is None:
        reasons.append("MISSING_SIGNAL_STRENGTH")

    if regime is None:
        reasons.append("MISSING_REGIME")

    # ----------------------------------------------------------------------------------------------
    # ARM SAFETY
    # ----------------------------------------------------------------------------------------------

    arms = [
        market_available,
        positioning_available,
        news_available,
    ]

    if any(x is None for x in arms):
        reasons.append("UNKNOWN_ARM_STATE")

    # Conservative rule:
    # all three arms must be available before trade eligibility.
    if not all(x == 1 for x in arms if x is not None):
        reasons.append("INCOMPLETE_ARM_SET")

    # ----------------------------------------------------------------------------------------------
    # FINAL DECISION
    # ----------------------------------------------------------------------------------------------

    eligible = len(reasons) == 0

    if eligible:
        status = "TRADE_ELIGIBLE"
    else:
        status = "NO_TRADE"

    return {
        "id": row_id,
        "asset": asset,
        "timestamp": timestamp,
        "direction": direction,
        "confidence": confidence,
        "regime": regime,
        "signal_strength": signal_strength,
        "data_quality": data_quality,
        "entry_price": entry_price,
        "available_weight": available_weight,
        "missing_arm_penalty": missing_arm_penalty,
        "market_available": market_available,
        "positioning_available": positioning_available,
        "news_available": news_available,
        "status": status,
        "eligible": eligible,
        "reasons": reasons,
    }


# --------------------------------------------------------------------------------------------------
# REPORT
# --------------------------------------------------------------------------------------------------

def build_report(
    production_before,
    production_after,
    capture_db,
    snapshot_id,
    evaluations,
):
    eligible = [
        x for x in evaluations
        if x["eligible"]
    ]

    no_trade = [
        x for x in evaluations
        if not x["eligible"]
    ]

    return {
        "frontier": "LIVE_SIGNAL_ELIGIBILITY_NO_TRADE_GATE_v0.1",
        "timestamp_utc": utc_now().isoformat(),

        "production_db": {
            "path": PRODUCTION_DB,
            "before": production_before,
            "after": production_after,
            "unchanged": (
                production_before == production_after
            ),
        },

        "capture_db": capture_db,

        "engine": EXPECTED_ENGINE,

        "snapshot_id": snapshot_id,

        "gate_configuration": {
            "min_confidence": MIN_CONFIDENCE,
            "min_available_weight": MIN_AVAILABLE_WEIGHT,
            "required_data_quality": REQUIRED_DATA_QUALITY,
            "required_safety": REQUIRED_SAFETY,
            "blocked_signal_strength": sorted(
                BLOCKED_SIGNAL_STRENGTH
            ),
            "blocked_directions": sorted(
                BLOCKED_DIRECTIONS
            ),
            "required_arms": [
                "market",
                "positioning",
                "news",
            ],
        },

        "rows": len(evaluations),

        "eligible_rows": len(eligible),

        "no_trade_rows": len(no_trade),

        "decision": (
            "TRADE_CANDIDATES_PRESENT"
            if eligible
            else "NO_TRADE"
        ),

        "row_results": evaluations,

        "safety": {
            "production_db_modified": False,
            "engine_executed": False,
            "historical_repair": False,
            "direction_inference": False,
            "score_reconstruction": False,
            "synthetic_data": False,
            "live_data_injection": False,
            "order_execution": False,
        },
    }


# --------------------------------------------------------------------------------------------------
# MAIN
# --------------------------------------------------------------------------------------------------

def main():

    print("=" * 100)
    print("ARUNDA TRADER LIVE SIGNAL ELIGIBILITY + NO-TRADE SAFETY GATE v0.1")
    print("=" * 100)

    print("OBJECTIVE:")
    print("  Evaluate ONLY the newest FUSION_v0.5 snapshot.")
    print("  Determine trade eligibility or NO-TRADE.")
    print()
    print("Production DB writes       : FORBIDDEN")
    print("Production engine run      : NO")
    print("Historical repair          : NONE")
    print("Direction inference        : NONE")
    print("Score reconstruction       : NONE")
    print("Synthetic data             : FORBIDDEN")
    print("Live data injection        : NONE")
    print("Order execution            : NONE")

    print()
    print("=" * 100)
    print("PRODUCTION BASELINE")
    print("=" * 100)

    production_before = production_baseline()

    print(f"Rows   : {production_before['rows']}")
    print(f"Size   : {production_before['size']}")
    print(f"SHA256 : {production_before['sha256']}")

    # ----------------------------------------------------------------------------------------------
    # CAPTURE
    # ----------------------------------------------------------------------------------------------

    latest = find_latest_capture()

    if not latest:
        raise RuntimeError(
            "No disposable live capture DB found."
        )

    capture_dir, capture_db = latest

    print()
    print("=" * 100)
    print("LIVE CAPTURE")
    print("=" * 100)

    print(f"Directory : {capture_dir}")
    print(f"Database  : {capture_db}")
    print(f"Size      : {os.path.getsize(capture_db)}")

    # ----------------------------------------------------------------------------------------------
    # READ-ONLY CAPTURE
    # ----------------------------------------------------------------------------------------------

    conn = open_readonly(capture_db)

    try:

        columns = get_columns(conn)

        required_columns = {
            "id",
            "timestamp",
            "asset",
            "market_available",
            "positioning_available",
            "news_available",
            "available_weight",
            "missing_arm_penalty",
            "data_quality",
            "direction",
            "confidence",
            "regime",
            "signal_strength",
            "entry_price",
            "fused_score",
            "snapshot_id",
            "engine_version",
        }

        missing = sorted(required_columns - columns)

        print()
        print("=" * 100)
        print("ELIGIBILITY INPUT CONTRACT")
        print("=" * 100)

        if missing:
            print("CONTRACT : FAIL")
            print("Missing columns:", missing)
            raise RuntimeError(
                f"Eligibility contract failed: {missing}"
            )

        print("CONTRACT : PASS")

        snapshot_id, rows = load_latest_snapshot(conn)

        print()
        print("=" * 100)
        print("CURRENT LIVE SNAPSHOT")
        print("=" * 100)

        print(f"Snapshot : {snapshot_id}")
        print(f"Rows     : {len(rows)}")

        if not rows:
            raise RuntimeError(
                "Current FUSION_v0.5 snapshot contains no rows."
            )

        # ------------------------------------------------------------------------------------------
        # EVALUATE
        # ------------------------------------------------------------------------------------------

        evaluations = [
            evaluate_row(row)
            for row in rows
        ]

    finally:
        conn.close()

    # ----------------------------------------------------------------------------------------------
    # RESULTS
    # ----------------------------------------------------------------------------------------------

    print()
    print("=" * 100)
    print("SIGNAL ELIGIBILITY MATRIX")
    print("=" * 100)

    print(
        "ID | ASSET | DIR   | CONF     | QUALITY  | "
        "STRENGTH | ARMS | RESULT"
    )
    print("-" * 100)

    for r in evaluations:

        arms = (
            f"{r['market_available']}/"
            f"{r['positioning_available']}/"
            f"{r['news_available']}"
        )

        print(
            f"{r['id']:2d} | "
            f"{r['asset']:<5} | "
            f"{str(r['direction']):<5} | "
            f"{r['confidence']!s:<8} | "
            f"{str(r['data_quality']):<8} | "
            f"{str(r['signal_strength']):<8} | "
            f"{arms:<5} | "
            f"{r['status']}"
        )

    print()
    print("=" * 100)
    print("NO-TRADE REASONS")
    print("=" * 100)

    for r in evaluations:

        if not r["eligible"]:

            print(
                f"id={r['id']} asset={r['asset']} "
                f"direction={r['direction']}"
            )

            for reason in r["reasons"]:
                print(f"  - {reason}")

    eligible_count = sum(
        1 for r in evaluations
        if r["eligible"]
    )

    no_trade_count = len(evaluations) - eligible_count

    print()
    print("=" * 100)
    print("ELIGIBILITY SUMMARY")
    print("=" * 100)

    print(f"TRADE_ELIGIBLE : {eligible_count}")
    print(f"NO_TRADE       : {no_trade_count}")

    # ----------------------------------------------------------------------------------------------
    # PRODUCTION INVARIANT
    # ----------------------------------------------------------------------------------------------

    production_after = production_baseline()

    unchanged = (
        production_before == production_after
    )

    print()
    print("=" * 100)
    print("PRODUCTION DATABASE INVARIANT")
    print("=" * 100)

    print(
        f"Before rows : {production_before['rows']}"
    )
    print(
        f"After rows  : {production_after['rows']}"
    )

    print(
        f"Before size : {production_before['size']}"
    )
    print(
        f"After size  : {production_after['size']}"
    )

    print(
        f"Before SHA256 : {production_before['sha256']}"
    )
    print(
        f"After SHA256  : {production_after['sha256']}"
    )

    print(
        "PRODUCTION DB INVARIANT : "
        + ("PASS" if unchanged else "FAIL")
    )

    if not unchanged:
        raise RuntimeError(
            "CRITICAL: Production DB changed."
        )

    # ----------------------------------------------------------------------------------------------
    # FINAL VERDICT
    # ----------------------------------------------------------------------------------------------

    report = build_report(
        production_before,
        production_after,
        capture_db,
        snapshot_id,
        evaluations,
    )

    report_name = (
        "LIVE_SIGNAL_ELIGIBILITY_NO_TRADE_REPORT.json"
    )

    report_path = PROJECT_ROOT / "LIVE_SIGNAL_ELIGIBILITY_NO_TRADE_REPORT.json"

    with open(
        report_path,
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            report,
            f,
            indent=2,
            ensure_ascii=False,
        )

    print()
    print("=" * 100)
    print("LIVE SIGNAL ELIGIBILITY + NO-TRADE SAFETY VERDICT")
    print("=" * 100)

    print(
        "ELIGIBILITY_EVALUATION : PASS"
    )

    print(
        "PRODUCTION_ISOLATION   : PASS"
    )

    print(
        "ORDER_EXECUTION        : NONE"
    )

    if eligible_count > 0:
        print(
            "FRONTIER VERDICT       : "
            "TRADE_CANDIDATES_PRESENT"
        )
    else:
        print(
            "FRONTIER VERDICT       : "
            "NO_TRADE"
        )

    print()
    print("Runtime report :", report_path)

    print()
    print("=" * 100)
    print("FINAL SAFETY VERDICT")
    print("=" * 100)

    print("Production DB writes : NONE")
    print("INSERT               : NONE")
    print("UPDATE               : NONE")
    print("DELETE               : NONE")
    print("DDL                  : NONE")
    print("Production engine    : NOT EXECUTED")
    print("Historical repair    : NONE")
    print("Direction inference  : NONE")
    print("Score reconstruction : NONE")
    print("Synthetic data       : NONE")
    print("Live data injection  : NONE")
    print("Order execution      : NONE")

    print()
    print(
        "The eligibility gate is analytical only."
    )
    print(
        "NO order or trading action is performed."
    )


if __name__ == "__main__":
    main()